package_name: 'gazebo_satellite_terrain'

zoom: 18
approx_origin_lat: 55.74664268169444
approx_origin_lon: 12.556765912443149
tile_size_pixels: 512
map_size: 3 # How many tiles to make the map n x n
prefetch_terrain: True
prespawn_terrain: True
gazebo_world_file: 'worlds/empty.world' # Relative to share dir
model_name: 'satellite_tile' # Shouldnt change, this is the name of directory the model is in models/satellite_tile - the name is also in the model.sdf file
